export const settingsActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_SMALL_LOGO : 'SET_SMALL_LOGO',
    SET_SOCIAL_MEDIA : 'SET_SOCIAL_MEDIA',
    SET_DEFAULT_MENU_IMAGE : 'SET_DEFAULT_MENU_IMAGE',
    SET_MENU_CONTENT : 'SET_MENU_CONTENT',
    SET_MENU_LOGO : 'SET_MENU_LOGO',
    SET_MENU_VISIBILITY : 'SET_MENU_VISIBILITY',
    SET_MENU_ITEMS : 'SET_MENU_ITEMS',
}